version: '3.4'

services:
  api:
    depends_on:
      - db
    image: strapi/strapi
    restart: unless-stopped
    container_name: strapi
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: db_strapi_name
      DATABASE_USERNAME: db_user
      DATABASE_PASSWORD: secret
      DATABASE_SSL: "false"
    ports: 
      - 8080:1337
    volumes:
      - ./app:/var/www/html/app

  db:
    image: mariadb:latest
    container_name: strapi_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_strapi_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: secret
